services:
  - type: web
    name: flightvision-1
    runtime: python
    repo: https://github.com/Miraj995/flightvision
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: AVIATIONSTACK_KEY
        value: 8c60ba3e7890b8c32671106be1753775
      - key: DATABASE_URL
        value: postgresql://flightvision_db_user:VqudVy31XoYxLDkwsCQxlkdHIqgOdn9r@dpg-d0monu6mcj7s739gfmm0-a.oregon-postgres.render.com/flightvision_db
      - key: SECRET_KEY
        value: flightvision-secret-key
      - key: ICAO_CODE
        value: VABB

