"""Add Flight and Advertisement models

Revision ID: 395a27bb334c
Revises: 
Create Date: 2025-05-19 21:20:34.982514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395a27bb334c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arrival', sa.String(length=100), nullable=False),
    sa.Column('departure', sa.String(length=100), nullable=False),
    sa.Column('gate', sa.String(length=10), nullable=True),
    sa.Column('baggage_belt', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
